version: "3.8"

services:
  wpokt-localnet:
    image: dan13ram/wpokt-localnet
    build:
      context: .
      target: base
    command: "/app/docker/entrypoint.sh"
    ports:
      - "8545:8545"
    expose:
      - "8545"
